FROM jenkins/jenkins:lts
USER root
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
	&& apt -y update \
	&& apt install -y nodejs \
	&& dpkg-reconfigure tzdata
RUN npm install junit-viewer -g
COPY --chown=jenkins:jenkins ./soapui/ /opt/soapui/
USER jenkins

